= Fractionizer
:source-highlighter: prettify
//                   coderay highlightjs prettify pygments
:coderay-linenums-mode: inline

ifdef::env-github[]
:imagesdir: https://cdn.rawgit.com/ajneu/fractionizer/master/images
endif::[]

ifndef::env-github[]
:imagesdir: https://cdn.rawgit.com/ajneu/fractionizer/master/images
//images
:toc:
endif::[]

C++ class to convert floating point values to fractions, by using continued fractions.

How this works is best shown by an example:

image::example_frac.svg[Continued Fraction]

The continued fraction has only integer whole numbers, that can be expressed in a vector:

image::vector_example.svg[]

As a formula-equation, the generation of continued fractions can be expressed as:

image::equation.svg[Equation]
(with `frac(x)` as shown https://en.wikipedia.org/wiki/Fractional_part[here])

As can be seen from the formula-equation above, given a number image:x_i.svg[]: +
If this number is not yet an integer (whole number)

* we truncate the number, so that we get an integer (whole number): image:whole.svg[] +
and then
* calculate the reciprocal of the fractional part image:reciprocal.svg[], to get the next number image:x_i1.svg[] +
and recursion...

We end, when we get a image:x_j.svg[] that is a whole number.

This gives as a vector of whole numbers:

image::vector.svg[]

representing a continued fraction:

image::cont_frac.svg[]

So much for idealized math. 

But given a computers floating point with limited precision (`float`, `double`, `long double`), the program calculates the resulting value of the continued fraction, at each new image:w_i.svg[] and compares it to image:x_i.svg[]

image::vectors.svg[]

The program stops, when we are close enough to image:x_i.svg[].

== Comments

Printing floating point numbers, so that the text (when read back in) is equivalent to the original floating point number, is not as easy as it seems. +
This roundtrip (floating number to text and back to floating number) can be tested nicely as follows:
[source,cpp]
----
double num  = 22.345;
double num2;
assert((std::istringstream(Print_float::print(num)) >> num2) && (num == num2));
----
This uses `Print_float::print()` (https://github.com/ajneu/fractionizer/blob/master/src/print_float.h#L11[ref]), which will always print a floating point number correctly, so that the roundtrip works! +
The clue is to use `oss << std::setprecision(std::numeric_limits<Tfl>::max_digits10)` (https://github.com/ajneu/fractionizer/blob/master/src/print_float.h#L14[ref]) as documented http://en.cppreference.com/w/cpp/types/numeric_limits/max_digits10[here].

=== Caution

The code currently uses 
[source,cpp]
----
      do {
      //while (std::abs((Fractionizer::calc_frac<Tfl>(vec, num, denom) - val)/val) > numeric_limits<Tfl>::min());
      while (Fractionizer::calc_frac<Tfl>(vec, num, denom) != val);
----
(https://github.com/ajneu/fractionizer/blob/master/src/fractionizer.h#L69[ref]) +
Up till now, the loop has always ended nicely. But I have no proof that it is safe, and it might be better to use some threshold comparision (the comment shows a possibility). If you can provide an example where the loop will not end, or furnish a proof that it will always end, then please let me know!

== Using computer calculators (PARI/GP and Calc)

=== PARI/GP

http://pari.math.u-bordeaux.fr

[source,bash]
----
apt-get install pari-gp
----

Use e.g.
[source,bash]
----
echo "1+2*3" | gp -f -q   -s 60M   -D realprecision=100
----

==== `bestappr` function

Use `bestappr` to get fraction approximations, with the given realprecision.

[source,bash]
----
echo "bestappr(22.345)" | gp -f -q   -s 60M   -D realprecision=100
----

where `gp --help` shows
[source,bash]
----
### Usage: gp [options] [GP files]
Available options:
[-f,--fast]	     Fast start: do not read .gprc
[-q,--quiet]	     Quiet mode: do not print banner and history numbers
[-s stacksize]	     Start with the PARI stack of given size (in bytes)
...
----

(so `-f` causes `gp` to start, without reading `.gprc` and without reading `/etc/gprc`)

and `man gp` shows
[source,bash]
----
   -D, --default key=val
       performs default(key, val); on startup, overriding values from the gprc preferences file. 'val' must be a constant value and is not
       allowed to involve any computation (e.g. 1+1 is forbidden). Any number of such default-setting statements may appear on the command
       line.
----						 

With PARI/GP, you can use much higher precision, than what a normal `long double` gives you. Try:
[source,bash]
----
echo "bestappr(7.402001334000000000000000000000000001)" | gp -f -q -s 60M -D realprecision=38
echo "bestappr(7.402001334000000000000000000000000001)" | gp -f -q -s 60M -D realprecision=100
echo "bestappr(7.402001334000000000000000000000000001)" | gp -f -q -s 60M -D realprecision=120
echo "bestappr(7.402001334000000000000000000000000001)" | gp -f -q -s 60M -D realprecision=136
----

==== `contfrac` function

Use `contfrac` to get the continous fraction whole-numbers (with the given realprecision).

[source,bash]
----
echo "contfrac(7.402001334000000000000000000000000001)" | gp -f -q -s 60M -D realprecision=38
echo "contfrac(7.402001334000000000000000000000000001)" | gp -f -q -s 60M -D realprecision=100
echo "contfrac(7.402001334000000000000000000000000001)" | gp -f -q -s 60M -D realprecision=120
echo "contfrac(7.402001334000000000000000000000000001)" | gp -f -q -s 60M -D realprecision=136
----

=== Calc

http://www.isthe.com/chongo/tech/comp/calc/

[source,bash]
----
apt-get install apcalc
----

Use e.g.
[source,bash]
----
calc -p 'c=config("mode", "frac"); 7.402001334000000000000000000000000001'
----
